version: "3.9"

services:
  bot:
    build: .
    container_name: FortyTwoDiscord
    env_file: .env
    
    restart: always

    volumes:
      - ./audio:/app/audio
      - ./vosk-model:/app/vosk-model
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
